// Code generated by sqlc. DO NOT EDIT.

package seequell

import (
	"database/sql"
	"time"
)

type Project struct {
	ID          int64          `json:"id"`
	ProjectName string         `json:"project_name"`
	ProjectDesc sql.NullString `json:"project_desc"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProjectUser struct {
	UserID    int64 `json:"user_id"`
	ProjectID int64 `json:"project_id"`
}

type User struct {
	ID          int64          `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	MiddleName  sql.NullString `json:"middle_name"`
	GoesBy      sql.NullString `json:"goes_by"`
	Email       string         `json:"email"`
	Pw          string         `json:"pw"`
	Gender      sql.NullString `json:"gender"`
	Ethnicity   sql.NullString `json:"ethnicity"`
	Position    sql.NullString `json:"position"`
	Institution sql.NullString `json:"institution"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
