// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UpdateProject struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type UpdateUser struct {
	ID          string `json:"id"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	GoesBy      string `json:"goesBy"`
	MiddleName  string `json:"middleName"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	Ethnicity   string `json:"ethnicity"`
	Position    string `json:"position"`
	Institution string `json:"institution"`
	IsActive    bool   `json:"isActive"`
}
