// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Meeting struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	People          []*User    `json:"people"`
	Projects        []*Project `json:"projects"`
	StartTime       time.Time  `json:"startTime"`
	DurationMinutes int        `json:"durationMinutes"`
}

type NewMeeting struct {
	Name            string    `json:"name"`
	PeopleIDs       []*string `json:"peopleIDs"`
	ProjectIDs      []*string `json:"projectIDs"`
	StartTime       time.Time `json:"startTime"`
	DurationMinutes int       `json:"durationMinutes"`
}

type ProjectListItem struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Slug      string  `json:"slug"`
	Personnel []*User `json:"personnel"`
}
