// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Meeting struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	People          []*User    `json:"people"`
	Projects        []*Project `json:"projects"`
	StartTime       time.Time  `json:"startTime"`
	DurationMinutes int        `json:"durationMinutes"`
}

type MeetingDetails struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	People          []*User        `json:"people"`
	Projects        []*Project     `json:"projects"`
	MeetingItems    []*MeetingItem `json:"meetingItems"`
	StartTime       time.Time      `json:"startTime"`
	DurationMinutes int            `json:"durationMinutes"`
}

type MeetingItem struct {
	ID                      string         `json:"id"`
	Personnel               *User          `json:"personnel"`
	PlannedAttendanceStatus string         `json:"plannedAttendanceStatus"`
	ActualAttendanceStatus  string         `json:"actualAttendanceStatus"`
	AttendanceReason        *string        `json:"attendanceReason"`
	Notes                   []*MeetingNote `json:"notes"`
}

type MeetingItemInput struct {
	ID                      string              `json:"id"`
	Personnel               string              `json:"personnel"`
	PlannedAttendanceStatus string              `json:"plannedAttendanceStatus"`
	ActualAttendanceStatus  string              `json:"actualAttendanceStatus"`
	AttendanceReason        *string             `json:"attendanceReason"`
	Notes                   []*MeetingNoteInput `json:"notes"`
}

type MeetingListItem struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	StartTime time.Time `json:"startTime"`
}

type MeetingNote struct {
	ID        string            `json:"id"`
	About     *User             `json:"about"`
	Author    *User             `json:"author"`
	Text      string            `json:"text"`
	Tags      []*MeetingNoteTag `json:"tags"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

type MeetingNoteInput struct {
	ID        *string                `json:"id"`
	About     string                 `json:"about"`
	Author    string                 `json:"author"`
	Text      string                 `json:"text"`
	Tags      []*MeetingNoteTagInput `json:"tags"`
	CreatedAt time.Time              `json:"createdAt"`
	UpdatedAt time.Time              `json:"updatedAt"`
}

type MeetingNoteTag struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type MeetingNoteTagInput struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type NewPersonnel struct {
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	GoesBy      *string `json:"goesBy"`
	MiddleName  *string `json:"middleName"`
	Email       string  `json:"email"`
	Gender      *string `json:"gender"`
	Ethnicity   *string `json:"ethnicity"`
	Position    *string `json:"position"`
	Institution *string `json:"institution"`
}

type NewProjectMeeting struct {
	Name            string    `json:"name"`
	ProjectIDs      []*string `json:"projectIDs"`
	StartTime       time.Time `json:"startTime"`
	DurationMinutes int       `json:"durationMinutes"`
}

type NewUserMeeting struct {
	Name            string    `json:"name"`
	PeopleIDs       []*string `json:"peopleIDs"`
	StartTime       time.Time `json:"startTime"`
	DurationMinutes int       `json:"durationMinutes"`
}

type PeopleMeetingDetails struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	People          []*User        `json:"people"`
	MeetingItems    []*MeetingItem `json:"meetingItems"`
	StartTime       time.Time      `json:"startTime"`
	DurationMinutes int            `json:"durationMinutes"`
}

type ProjectListItem struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Slug      string  `json:"slug"`
	Personnel []*User `json:"personnel"`
}

type UpdateMeetingItemRequest struct {
	ID                      string              `json:"id"`
	PersonnelID             string              `json:"personnelID"`
	PlannedAttendanceStatus string              `json:"plannedAttendanceStatus"`
	ActualAttendanceStatus  string              `json:"actualAttendanceStatus"`
	AttendanceReason        string              `json:"attendanceReason"`
	Notes                   []*MeetingNoteInput `json:"notes"`
}

type UpdatedPeopleMeetingDetails struct {
	ID              string              `json:"id"`
	Name            string              `json:"name"`
	People          []*string           `json:"people"`
	MeetingItems    []*MeetingItemInput `json:"meetingItems"`
	StartTime       time.Time           `json:"startTime"`
	DurationMinutes int                 `json:"durationMinutes"`
}
